/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelineIndexRouteImport } from './routes/pipeline/index'
import { Route as MediaVideoIdRouteImport } from './routes/media/$videoId'
import { Route as PipelineVideoIdTabRouteImport } from './routes/pipeline/$videoId/$tab'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelineRoute,
} as any)
const MediaVideoIdRoute = MediaVideoIdRouteImport.update({
  id: '/media/$videoId',
  path: '/media/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineVideoIdTabRoute = PipelineVideoIdTabRouteImport.update({
  id: '/$videoId/$tab',
  path: '/$videoId/$tab',
  getParentRoute: () => PipelineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/editor': typeof EditorRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/studio': typeof StudioRoute
  '/media/$videoId': typeof MediaVideoIdRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/pipeline/$videoId/$tab': typeof PipelineVideoIdTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/editor': typeof EditorRoute
  '/studio': typeof StudioRoute
  '/media/$videoId': typeof MediaVideoIdRoute
  '/pipeline': typeof PipelineIndexRoute
  '/pipeline/$videoId/$tab': typeof PipelineVideoIdTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/editor': typeof EditorRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/studio': typeof StudioRoute
  '/media/$videoId': typeof MediaVideoIdRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/pipeline/$videoId/$tab': typeof PipelineVideoIdTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batch'
    | '/editor'
    | '/pipeline'
    | '/studio'
    | '/media/$videoId'
    | '/pipeline/'
    | '/pipeline/$videoId/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batch'
    | '/editor'
    | '/studio'
    | '/media/$videoId'
    | '/pipeline'
    | '/pipeline/$videoId/$tab'
  id:
    | '__root__'
    | '/'
    | '/batch'
    | '/editor'
    | '/pipeline'
    | '/studio'
    | '/media/$videoId'
    | '/pipeline/'
    | '/pipeline/$videoId/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchRoute: typeof BatchRoute
  EditorRoute: typeof EditorRoute
  PipelineRoute: typeof PipelineRouteWithChildren
  StudioRoute: typeof StudioRoute
  MediaVideoIdRoute: typeof MediaVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/': {
      id: '/pipeline/'
      path: '/'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/media/$videoId': {
      id: '/media/$videoId'
      path: '/media/$videoId'
      fullPath: '/media/$videoId'
      preLoaderRoute: typeof MediaVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/$videoId/$tab': {
      id: '/pipeline/$videoId/$tab'
      path: '/$videoId/$tab'
      fullPath: '/pipeline/$videoId/$tab'
      preLoaderRoute: typeof PipelineVideoIdTabRouteImport
      parentRoute: typeof PipelineRoute
    }
  }
}

interface PipelineRouteChildren {
  PipelineIndexRoute: typeof PipelineIndexRoute
  PipelineVideoIdTabRoute: typeof PipelineVideoIdTabRoute
}

const PipelineRouteChildren: PipelineRouteChildren = {
  PipelineIndexRoute: PipelineIndexRoute,
  PipelineVideoIdTabRoute: PipelineVideoIdTabRoute,
}

const PipelineRouteWithChildren = PipelineRoute._addFileChildren(
  PipelineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchRoute: BatchRoute,
  EditorRoute: EditorRoute,
  PipelineRoute: PipelineRouteWithChildren,
  StudioRoute: StudioRoute,
  MediaVideoIdRoute: MediaVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
